from decouple import config

GMAIL_SMTP_SENDER_ACCOUNT_USERNAME = config('GMAIL_SMTP_SENDER_ACCOUNT_USERNAME', default=None)
GMAIL_SMTP_SENDER_ACCOUNT_PASSWORD = config('GMAIL_SMTP_SENDER_ACCOUNT_PASSWORD', default=None)
GMAIL_SMTP_SESSION_HOST = config('GMAIL_SMTP_SESSION_HOST', default='smtp.gmail.com')
GMAIL_SMTP_SESSION_PORT = config('GMAIL_SMTP_SESSION_PORT', default=587, cast=int)
NOTIFICATION_EMAIL_RECIPIENT = config('NOTIFICATION_EMAIL_RECIPIENT', default=None)
NOTIFICATION_EMAIL_SUBJECT = 'UK Travel Restrictions update'
SAFE_COUNTRIES_LIST_PICKLE_FILE_NAME = 'save_countries_up_until_now.p'
CHECK_FOR_UPDATES_INTERVAL_IN_SECONDS = config('CHECK_FOR_UPDATES_INTERVAL_IN_SECONDS', default=10800, cast=int)
d = 5